name = "WorldWarSMP"
author = "XxLegitOPxX"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4f38981ec01f80efa74911836f4605cb32d694f0d67d96a494c4f9b48ad88eb"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
