name = "WorldWarSMP"
author = "XxLegitOPxX"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcba13a3d518b28a1048aabe9df9c70d3275f061a967450b3ad8bdff2ce1b05c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
