name = "WorldWarSMP"
author = "XxLegitOPxX"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c6e8bfb4aaded45d76635b28cb478d20d9db8c163e285fc8ed3e3d73a344c1a"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
