name = "WorldWarSMP"
author = "XxLegitOPxX"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a2874546ab9722c7e21088b9a617a37f6d2f6a27e414ffeb604413a8f6ffab4"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
