name = "WorldWarSMP (Server)"
author = "XxLegitOPxX"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e45ea188f3d6b88f9c5b8f4a5f777acfd7ef71e3f5fbd16dc8e25eb971416090"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
