name = "WorldWarSMP (Server)"
author = "XxLegitOPxX"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66e769cc52485e701ca99f4d58a55ee13c50684dceb2e15f39023be8643e31ab"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
