name = "WorldWarSMP (Server)"
author = "XxLegitOPxX"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96703df841c7344b470175ace21012de506e68a855678359b1d325b863030338"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
