name = "WorldWarSMP (Server)"
author = "XxLegitOPxX"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e71e5ad5979bad9779aff8e3f480e25a05f42448526422fda965af3af71b84e5"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
