name = "WorldWarSMP (Server)"
author = "XxLegitOPxX"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6372128ff22ac2eb16fe50d4f1b8123ce3d70c7a4938da84b765b0f0fb842888"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
