name: Deploy modpacks to GitHub Pages

on:
  push:
    tags: ["*"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Prepare deployment folders
        run: |
          mkdir -p deployment/forge
          cp -r forge/client deployment/forge/
          cp -r forge/server deployment/forge/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deployment
          publish_branch: gh-pages
