name: packwiz installer github pages

on:
  push:
    tags: ["*"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Prepare deployment folders
        run: |
          mkdir -p deployment
          cp -r forge/client deployment/
          cp -r forge/server deployment/
          cp -r forge/testing deployment/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deployment
          publish_branch: gh-pages
